In [1]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats

## List 11 - Гетероскедастичность

## Задача 1.2

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/artamonoff/Econometrica/master/python-notebooks/data-csv/wage1.csv')

In [3]:
model = smf.ols(data = df, formula = 'np.log(wage)~exper+I(exper**2)+female+married+smsa').fit()
model.params

Intercept        1.250423
exper            0.036880
I(exper ** 2)   -0.000772
female          -0.362740
married          0.143784
smsa             0.272562
dtype: float64

$$
Тест \ Уайта
$$
\
$$
e_i = y_i - \hat{y_i}
$$
\
$$
e_i^2 = \gamma_0 + \gamma_1*totwrk+age+\gamma_2*I(age**2)+\gamma_3*male+\gamma_3*smsa+\gamma_4*south
$$

In [4]:
# квадраты остатков добавим в датафрейм, воспользовавшись методом '.resid', возвращающий значения остатков
df['res2']=model.resid**2
df['res']=model.resid

In [5]:
BP_model = smf.ols(data=df, formula='res2~exper+I(exper**2)+female+married+smsa').fit()
BP_model.params

Intercept        0.158840
exper            0.011373
I(exper ** 2)   -0.000238
female          -0.029665
married         -0.063965
smsa             0.017782
dtype: float64

$$
H_0: \gamma_1 = \gamma_2 = \gamma_3 = \gamma_4 = \gamma_5 = 0
    $$\
    $$
    H_1: \gamma_1^2 + \gamma_2^2 + \gamma_3^2 + \gamma_4^2 + \gamma_5^2 > 0
    $$

In [6]:
# Zнабл=n*R^2 и для проверки гипотезы на справедливость имеет распределение хи-квадрат
Z_nabl = len(df)*BP_model.rsquared
Z_nabl

8.939857776687509

In [7]:
Hi2 = stats.chi2.ppf(1-0.05,5)
Hi2

11.070497693516351

## Тест указыавет на гомоскедастичность, т.к. $Znabl<Zcrit$

## Задача 1.3

In [8]:
df = pd.read_csv('https://raw.githubusercontent.com/artamonoff/Econometrica/master/python-notebooks/data-csv/Labour.csv')

In [9]:
model = smf.ols(data = df, formula = 'np.log(output)~np.log(capital)+np.log(labour)+I(np.log(capital)**2)+I(np.log(labour)**2)').fit()
model.params

Intercept                 -1.303943
np.log(capital)            0.183108
np.log(labour)             0.515297
I(np.log(capital) ** 2)    0.022748
I(np.log(labour) ** 2)     0.020263
dtype: float64

In [10]:
# квадраты остатков добавим в датафрейм, воспользовавшись методом '.resid', возвращающий значения остатков
df['res2']=model.resid**2
df['res']=model.resid

In [11]:
BP_model = smf.ols(data=df, formula='res2~np.log(capital)+np.log(labour)+I(np.log(capital)**2)+I(np.log(labour)**2)').fit()
BP_model.params

Intercept                  1.455218
np.log(capital)           -0.031399
np.log(labour)            -0.497592
I(np.log(capital) ** 2)    0.011211
I(np.log(labour) ** 2)     0.045165
dtype: float64

In [12]:
# Zнабл=n*R^2 и для проверки гипотезы на справедливость имеет распределение хи-квадрат
Z_nabl = len(df)*BP_model.rsquared
Z_nabl

44.53371850842645

In [13]:
Hi2 = stats.chi2.ppf(1-0.05,4)
Hi2

9.487729036781154

In [14]:
df = pd.read_csv('https://raw.githubusercontent.com/artamonoff/Econometrica/master/python-notebooks/data-csv/icecream.csv')

## Тест указывает на гетероскедастичность, принимается гипотеза $H_1$

## Задача 1.4

In [15]:
df = pd.read_csv('https://raw.githubusercontent.com/artamonoff/Econometrica/master/python-notebooks/data-csv/Electricity.csv')

In [16]:
model = smf.ols(data = df, formula = 'np.log(cost)~np.log(q)+np.log(pl)+I(np.log(q)**2)+np.log(pk)+np.log(pf)').fit()
model.params

Intercept           -6.738661
np.log(q)            0.402981
np.log(pl)           0.146085
I(np.log(q) ** 2)    0.030440
np.log(pk)           0.157079
np.log(pf)           0.684705
dtype: float64

In [17]:
# квадраты остатков добавим в датафрейм, воспользовавшись методом '.resid', возвращающий значения остатков
df['res2']=model.resid**2
df['res']=model.resid

In [18]:
BP_model = smf.ols(data=df, formula='res2~np.log(q)+np.log(pl)+I(np.log(q)**2)+np.log(pk)+np.log(pf)').fit()
BP_model.params

Intercept           -0.162405
np.log(q)           -0.020364
np.log(pl)           0.024967
I(np.log(q) ** 2)    0.000863
np.log(pk)           0.029111
np.log(pf)          -0.017827
dtype: float64

In [19]:
# Zнабл=n*R^2 и для проверки гипотезы на справедливость имеет распределение хи-квадрат
Z_nabl = len(df)*BP_model.rsquared
Z_nabl

45.076181088303315

In [20]:
Hi2 = stats.chi2.ppf(1-0.05,5)
Hi2

11.070497693516351

## Тест указывает на гетероскедастичность, принимается гипотеза $H_1$

## Задача 2.2

In [21]:
# состоятельные std err в условиях гетероскедастичности
BP_model = smf.ols(data=df, formula='np.log(cost)~np.log(q)+np.log(pl)+I(np.log(q)**2)+np.log(pk)+np.log(pf)').fit(cov_type='HC3')
BP_model.summary(alpha=0.01).tables[1]

<class 'statsmodels.iolib.table.SimpleTable'>

In [22]:
t_cr = stats.t.ppf(1-0.01/2,len(df)-6)
t_cr

2.608560883167519

## Значимы все регрессоры, кроме log(pk) и log(pl)

## Задача 3.2.1

In [23]:
df['log_pl2']=np.log(df['pl'])**2
df['log_pf2']=np.log(df['pf'])**2

In [24]:
# состоятельные std err в условиях гетероскедастичности
BP_model = smf.ols(data=df, formula='np.log(cost)~np.log(q)+I(np.log(q)**2)+np.log(pl)+log_pl2+log_pf2+I(np.log(pk)**2)+np.log(pk)+np.log(pf)').fit(cov_type='HC3')
BP_model.summary(alpha=0.01).tables[1]

<class 'statsmodels.iolib.table.SimpleTable'>

In [25]:
# состоятельные std err в условиях гетероскедастичности
model = smf.ols(data=df, formula='np.log(cost)~np.log(q)+I(np.log(q)**2)+np.log(pl)+log_pl2+log_pf2+I(np.log(pk)**2)+np.log(pk)+np.log(pf)').fit()
model.summary(alpha=0.01).tables[1]

<class 'statsmodels.iolib.table.SimpleTable'>

In [26]:
f_test1 = model.f_test( 'np.log(pl)=log_pl2=0' ) 
f_test1.fvalue #будет показано только Fнабл

array([[3.47970133]])

In [27]:
f_test = BP_model.f_test( 'np.log(pl)=log_pl2=0' ) 
f_test.fvalue #будет показано только Fнабл.

array([[1.97801397]])

In [28]:
F_cr = stats.f.ppf(1-0.05, 2, len(df)-9)
F_cr

3.05677872616665

## Влияние коэффициентов незначимо. А ведь неробастный тест показывал обратное! Значит, эти коэффициенты влияют лишь на разброс, но не предсказывают значение $log(cost)$.

## Задача 3.2.3

In [29]:
f_test1 = model.f_test( 'np.log(pf)=log_pf2=0' ) 
f_test1.fvalue #будет показано только Fнабл

array([[129.37367052]])

In [30]:
f_test = BP_model.f_test( 'np.log(pf)=log_pf2=0' ) 
f_test.fvalue #будет показано только Fнабл.

array([[79.13102107]])

## Влияние коэффициентов значимо.

$$
------------------------------------------------------
$$

# List 12 - Автокорреляция

## Задача 1.1

In [41]:
df = pd.read_csv('https://raw.githubusercontent.com/artamonoff/Econometrica/master/python-notebooks/data-csv/icecream.csv')

In [47]:
model = smf.ols(data=df, formula = 'cons~income+price+temp').fit()
model.params

Intercept    0.197315
income       0.003308
price       -1.044413
temp         0.003458
dtype: float64

$$
cons_t = \beta_0 + \beta_1*price + \beta_2*temp + \beta_3*income
$$

$Предположим, что \ зависимость \ ошибок \ имеет \ вид:$
$$ u_t = u_0 + \rho*u_{t-1} $$

$$
H_0: \rho=0
    $$
    $$
H_1: \rho\neq 0
    $$

In [48]:
res_sum = sum(model.resid**2)

In [49]:
# Вычислим числитель
sum_resid = 0
#запускаем цикл
for i in range(len(model.resid)-1):
    sum_resid+=(model.resid[i+1]-model.resid[i])**2

In [50]:
sum_resid/res_sum

1.0211693122833825

## $DW<d1$, следовательно, гипотеза $H_0$ отвергается, наблюдается положительная корреляция

## Задача 3.1

In [55]:
# состоятельные HAC-s.e. в условиях гетероскедастичности
model = smf.ols(data=df, formula = 'cons~income+price+temp').fit(cov_type='HC3')
model.summary(alpha=0.01).tables[1]

<class 'statsmodels.iolib.table.SimpleTable'>

In [56]:
t_cr = stats.t.ppf(1-0.01/2, len(df)-4)
t_cr

2.7787145333289134

## Значим лишь коеффициент при $temp$

## Задача 1.2

In [36]:
df = pd.read_csv('https://raw.githubusercontent.com/artamonoff/Econometrica/master/python-notebooks/data-csv/Consumption.csv')

In [37]:
model = smf.ols(data=df, formula = 'np.log(yd)~np.log(ce)').fit()
model.params

Intercept    -0.392351
np.log(ce)    1.041314
dtype: float64

#### Не понял, как в модель добавить "дельту", чтобы учесть изменения предыдущих периодов. 

In [38]:
res_sum = sum(model.resid**2)

In [39]:
# Вычислим числитель
sum_resid = 0
#запускаем цикл
for i in range(len(model.resid)-1):
    sum_resid+=(model.resid[i+1]-model.resid[i])**2

In [40]:
sum_resid/res_sum

0.1871700336977041